afterInstall: yarn run format

packageExtensions:
   "@firebase/database@*":
      dependencies:
         "@firebase/app": "*"
         "@firebase/app-types": "*"
   "@firebase/auth@*":
      dependencies:
         "@firebase/app": "*"
         "@firebase/app-types": "*"
   "redux-persist@*":
      dependencies:
         "redux": "*"
   "next-sitemap@*":
      dependencies:
         "@next/env": "*"
   "@mui/x-date-pickers@*":
      dependencies:
         "@babel/runtime": "*"
   "intro.js-react@*":
      dependencies:
         "prop-types": "*"

plugins:
   -  path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
      spec: "@yarnpkg/plugin-interactive-tools"
   -  path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: "@yarnpkg/plugin-typescript"
   -  path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
      spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.3.1/bundles/@yarnpkg/plugin-after-install.js"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.0.cjs
