name: Deploy to Firebase Hosting
on:
   push:
      branches:
         - main
   pull_request:
jobs:
   build_and_deploy:
      runs-on: ubuntu-latest
      steps:
         -  name: checkout
            uses: actions/checkout@v3
         -  name: build
            env:
               env_file: ${{ secrets.ENV }}
            run: |
               echo "$env_file" > .env
               yarn
               yarn build
               yarn export
         -  name: deploy
            uses: FirebaseExtended/action-hosting-deploy@v0
            with:
               repoToken: '${{ secrets.GITHUB_TOKEN }}'
               firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AZUR_LANE_TRACKER }}'
               channelId: live
               projectId: azur-lane-tracker
