const ships = {
	'Universal_Bulin':                [ 'Universal Bulin', 'Elite', 'Universal', 'Destroyer', 3, 'DD', 'AA', 'AA' ],
	'Prototype_Bulin_MKII':           [ 'Prototype Bulin MKII', 'Super Rare', 'Universal', 'Destroyer', 3, 'DD', 'AA', 'AA' ],
	'Specialized_Bulin_Custom_MKIII': [ 'Specialized Bulin Custom MKIII', 'Ultra Rare', 'Universal', 'Destroyer', 3, 'DD', 'AA', 'AA' ],
	'Cassin':                         [ 'Cassin', 'Rare', 'Eagle Union', 'Destroyer', 2, 'DD', 'T', 'AA' ],
	'Downes':                         [ 'Downes', 'Rare', 'Eagle Union', 'Destroyer', 2, 'DD', 'T', 'AA' ],
	'Gridley':                        [ 'Gridley', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T*', 'AA' ],
	'Dewey':                          [ 'Dewey', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Aylwin':                         [ 'Aylwin', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Craven':                         [ 'Craven', 'Normal', 'Eagle Union', 'Destroyer', 3, 'DD', 'T*', 'AA' ],
	'McCall':                         [ 'McCall', 'Normal', 'Eagle Union', 'Destroyer', 3, 'DD', 'T*', 'AA' ],
	'Maury':                          [ 'Maury', 'Elite', 'Eagle Union', 'Destroyer', 3, 'DD', 'T*', 'AA' ],
	'Sims':                           [ 'Sims', 'Elite', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Hammann':                        [ 'Hammann', 'Elite', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA*' ],
	'Benson':                         [ 'Benson', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Laffey':                         [ 'Laffey', 'Super Rare', 'Eagle Union', 'Destroyer', 0.5, 'DD*', 'T', 'AA' ],
	'Bailey':                         [ 'Bailey', 'Elite', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Hobby':                          [ 'Hobby', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Kalk':                           [ 'Kalk', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T*', 'AA' ],
	'Fletcher':                       [ 'Fletcher', 'Rare', 'Eagle Union', 'Destroyer', 2, 'DD', 'T', 'AA' ],
	'Radford':                        [ 'Radford', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Jenkins':                        [ 'Jenkins', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Nicholas':                       [ 'Nicholas', 'Super Rare', 'Eagle Union', 'Destroyer', 2, 'DD*', 'T', 'AA' ],
	'Bache':                          [ 'Bache', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA*' ],
	'Stanly':                         [ 'Stanly', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA*' ],
	'Foote':                          [ 'Foote', 'Normal', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Spence':                         [ 'Spence', 'Normal', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Thatcher':                       [ 'Thatcher', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Kimberly':                       [ 'Kimberly', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Mullany':                        [ 'Mullany', 'Elite', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Bush':                           [ 'Bush', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Hazelwood':                      [ 'Hazelwood', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Smalley':                        [ 'Smalley', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Aulick':                         [ 'Aulick', 'Normal', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Charles_Ausburne':               [ 'Charles Ausburne', 'Elite', 'Eagle Union', 'Destroyer', 3, 'DD*', 'T', 'AA' ],
	'Halsey_Powell':                  [ 'Halsey Powell', 'Rare', 'Eagle Union', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Cooper':                         [ 'Cooper', 'Elite', 'Eagle Union', 'Destroyer', 2, 'DD', 'T', 'AA' ],
	'Eldridge':                       [ 'Eldridge', 'Super Rare', 'Eagle Union', 'Destroyer', 1.5, 'DD', 'T', 'AA' ],
	'Omaha':                          [ 'Omaha', 'Normal', 'Eagle Union', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Raleigh':                        [ 'Raleigh', 'Normal', 'Eagle Union', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Richmond':                       [ 'Richmond', 'Normal', 'Eagle Union', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Concord':                        [ 'Concord', 'Rare', 'Eagle Union', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Marblehead':                     [ 'Marblehead', 'Rare', 'Eagle Union', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Memphis':                        [ 'Memphis', 'Rare', 'Eagle Union', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Brooklyn':                       [ 'Brooklyn', 'Rare', 'Eagle Union', 'Light Cruiser', 1.5, 'CL', 'DD', 'AA' ],
	'Phoenix':                        [ 'Phoenix', 'Rare', 'Eagle Union', 'Light Cruiser', 1, 'CL', 'DD', 'AA' ],
	'Honolulu':                       [ 'Honolulu', 'Rare', 'Eagle Union', 'Light Cruiser', 2, 'CL', 'DD', 'AA' ],
	'St._Louis':                      [ 'St. Louis', 'Elite', 'Eagle Union', 'Light Cruiser', 1.5, 'CL', 'DD', 'AA*' ],
	'Helena':                         [ 'Helena', 'Super Rare', 'Eagle Union', 'Light Cruiser', 0, 'CL', 'DD', 'AA' ],
	'Lena':                           [ 'Lena', 'Elite', 'Eagle Union', 'Light Cruiser', 3, 'CL', 'DD', 'AA*' ],
	'Atlanta':                        [ 'Atlanta', 'Rare', 'Eagle Union', 'Light Cruiser', 3, 'CL/DD', 'T', 'AA*' ],
	'Juneau':                         [ 'Juneau', 'Rare', 'Eagle Union', 'Light Cruiser', 3, 'CL/DD', 'T', 'AA*' ],
	'San_Diego':                      [ 'San Diego', 'Ultra Rare', 'Eagle Union', 'Light Cruiser', 0, 'CL/DD', 'T', 'AA*' ],
	'San_Juan':                       [ 'San Juan', 'Rare', 'Eagle Union', 'Light Cruiser', 3, 'CL/DD', 'T', 'AA*' ],
	'Reno':                           [ 'Reno', 'Super Rare', 'Eagle Union', 'Light Cruiser', 1, 'CL/DD', 'T', 'AA' ],
	'Lil_Sandy':                      [ 'Lil Sandy', 'Elite', 'Eagle Union', 'Light Cruiser', 3, 'CL/DD', 'T', 'AA' ],
	'Cleveland':                      [ 'Cleveland', 'Elite', 'Eagle Union', 'Light Cruiser', 1.5, 'CL', 'DD', 'AA*' ],
	'Columbia':                       [ 'Columbia', 'Elite', 'Eagle Union', 'Light Cruiser', 1.5, 'CL', 'DD', 'AA*' ],
	'Montpelier':                     [ 'Montpelier', 'Super Rare', 'Eagle Union', 'Light Cruiser', 1, 'CL', 'DD', 'AA*' ],
	'Denver':                         [ 'Denver', 'Elite', 'Eagle Union', 'Light Cruiser', 1.5, 'CL', 'DD', 'AA*' ],
	'Birmingham':                     [ 'Birmingham', 'Elite', 'Eagle Union', 'Light Cruiser', 1, 'CL', 'DD', 'AA' ],
	'Biloxi':                         [ 'Biloxi', 'Elite', 'Eagle Union', 'Light Cruiser', 1, 'CL', 'DD', 'AA' ],
	'Clevelad':                       [ 'Clevelad', 'Elite', 'Eagle Union', 'Light Cruiser', 3, 'CL', 'DD', 'AA' ],
	'Cleveland_µ':                    [ 'Cleveland µ', 'Elite', 'Eagle Union', 'Light Cruiser', 2, 'CL', 'DD', 'AA' ],
	'Pensacola':                      [ 'Pensacola', 'Normal', 'Eagle Union', 'Heavy Cruiser', 3, 'CA', 'DD', 'AA' ],
	'Salt_Lake_City':                 [ 'Salt Lake City', 'Normal', 'Eagle Union', 'Heavy Cruiser', 3, 'CA', 'DD', 'AA' ],
	'Northampton':                    [ 'Northampton', 'Rare', 'Eagle Union', 'Heavy Cruiser', 2, 'CA', 'DD', 'AA' ],
	'Chicago':                        [ 'Chicago', 'Rare', 'Eagle Union', 'Heavy Cruiser', 1.5, 'CA*', 'DD', 'AA' ],
	'Houston':                        [ 'Houston', 'Elite', 'Eagle Union', 'Heavy Cruiser', 2, 'CA*', 'DD', 'AA' ],
	'Portland':                       [ 'Portland', 'Elite', 'Eagle Union', 'Heavy Cruiser', 0.5, 'CA', 'DD', 'AA' ],
	'Indianapolis':                   [ 'Indianapolis', 'Elite', 'Eagle Union', 'Heavy Cruiser', 2, 'CA', 'DD', 'AA' ],
	'Astoria':                        [ 'Astoria', 'Elite', 'Eagle Union', 'Heavy Cruiser', 3, 'CA', 'DD', 'AA' ],
	'Minneapolis':                    [ 'Minneapolis', 'Super Rare', 'Eagle Union', 'Heavy Cruiser', 0, 'CA', 'DD', 'AA' ],
	'Quincy':                         [ 'Quincy', 'Elite', 'Eagle Union', 'Heavy Cruiser', 3, 'CA', 'DD', 'AA' ],
	'Vincennes':                      [ 'Vincennes', 'Elite', 'Eagle Union', 'Heavy Cruiser', 3, 'CA', 'DD', 'AA' ],
	'Wichita':                        [ 'Wichita', 'Elite', 'Eagle Union', 'Heavy Cruiser', 1, 'CA*', 'DD', 'AA' ],
	'Baltimore':                      [ 'Baltimore', 'Super Rare', 'Eagle Union', 'Heavy Cruiser', 0, 'CA', 'DD', 'AA' ],
	'Bremerton':                      [ 'Bremerton', 'Super Rare', 'Eagle Union', 'Heavy Cruiser', 0.5, 'CA*', 'DD', 'AA' ],
	'Baltimore_µ':                    [ 'Baltimore µ', 'Elite', 'Eagle Union', 'Heavy Cruiser', 1, 'CA', 'DD', 'AA' ],
	'Nevada':                         [ 'Nevada', 'Rare', 'Eagle Union', 'Battleship', 2, 'BB*', 'DD', 'AA' ],
	'Oklahoma':                       [ 'Oklahoma', 'Rare', 'Eagle Union', 'Battleship', 2, 'BB*', 'DD', 'AA' ],
	'Pennsylvania':                   [ 'Pennsylvania', 'Rare', 'Eagle Union', 'Battleship', 1.5, 'BB', 'DD', 'AA' ],
	'Arizona':                        [ 'Arizona', 'Elite', 'Eagle Union', 'Battleship', 1.5, 'BB*', 'DD', 'AA' ],
	'Tennessee':                      [ 'Tennessee', 'Rare', 'Eagle Union', 'Battleship', 3, 'BB', 'DD', 'AA' ],
	'California':                     [ 'California', 'Rare', 'Eagle Union', 'Battleship', 3, 'BB*', 'DD', 'AA' ],
	'Colorado':                       [ 'Colorado', 'Elite', 'Eagle Union', 'Battleship', 3, 'BB*', 'DD', 'AA' ],
	'Maryland':                       [ 'Maryland', 'Elite', 'Eagle Union', 'Battleship', 3, 'BB*', 'DD', 'AA' ],
	'West_Virginia':                  [ 'West Virginia', 'Elite', 'Eagle Union', 'Battleship', 3, 'BB*', 'DD', 'AA' ],
	'North_Carolina':                 [ 'North Carolina', 'Super Rare', 'Eagle Union', 'Battleship', 1.5, 'BB', 'DD', 'AA' ],
	'Washington':                     [ 'Washington', 'Super Rare', 'Eagle Union', 'Battleship', 1, 'BB', 'DD', 'AA' ],
	'South_Dakota':                   [ 'South Dakota', 'Super Rare', 'Eagle Union', 'Battleship', 1.5, 'BB*', 'DD', 'AA' ],
	'Massachusetts':                  [ 'Massachusetts', 'Super Rare', 'Eagle Union', 'Battleship', 1, 'BB', 'DD', 'AA' ],
	'Alabama':                        [ 'Alabama', 'Super Rare', 'Eagle Union', 'Battleship', 0.5, 'BB', 'DD', 'AA' ],
	'Long_Island':                    [ 'Long Island', 'Elite', 'Eagle Union', 'Light Aircraft Carrier', 3, 'F*', 'DB*', 'AA' ],
	'Bogue':                          [ 'Bogue', 'Rare', 'Eagle Union', 'Light Aircraft Carrier', 3, 'F*', 'DB*', 'AA' ],
	'Casablanca':                     [ 'Casablanca', 'Rare', 'Eagle Union', 'Light Aircraft Carrier', 0.5, 'F*', 'TB*', 'AA' ],
	'Langley':                        [ 'Langley', 'Rare', 'Eagle Union', 'Light Aircraft Carrier', 2, 'F', 'F', 'DB' ],
	'Lexington':                      [ 'Lexington', 'Elite', 'Eagle Union', 'Aircraft Carrier', 2, 'F*', 'DB*', 'DB*' ],
	'Saratoga':                       [ 'Saratoga', 'Super Rare', 'Eagle Union', 'Aircraft Carrier', 0.5, 'F*', 'DB*', 'DB*' ],
	'Ranger':                         [ 'Ranger', 'Rare', 'Eagle Union', 'Light Aircraft Carrier', 1.5, 'TB*', 'DB*', 'DB*' ],
	'Yorktown':                       [ 'Yorktown', 'Elite', 'Eagle Union', 'Aircraft Carrier', 2, 'F*', 'DB*', 'TB*' ],
	'Enterprise':                     [ 'Enterprise', 'Super Rare', 'Eagle Union', 'Aircraft Carrier', 0, 'F*', 'DB*', 'TB*' ],
	'Wasp':                           [ 'Wasp', 'Rare', 'Eagle Union', 'Aircraft Carrier', 3, 'F*', 'DB*', 'TB*' ],
	'Hornet':                         [ 'Hornet', 'Elite', 'Eagle Union', 'Aircraft Carrier', 1.5, 'F*', 'DB*', 'TB*' ],
	'Essex':                          [ 'Essex', 'Super Rare', 'Eagle Union', 'Aircraft Carrier', 0, 'F*', 'DB*', 'TB*' ],
	'Intrepid':                       [ 'Intrepid', 'Super Rare', 'Eagle Union', 'Aircraft Carrier', 0.5, 'F*', 'DB*', 'TB*' ],
	'Bunker_Hill':                    [ 'Bunker Hill', 'Super Rare', 'Eagle Union', 'Aircraft Carrier', 0.5, 'F*', 'DB*', 'TB*' ],
	'Bataan':                         [ 'Bataan', 'Elite', 'Eagle Union', 'Light Aircraft Carrier', 1, 'F*', 'TB*', 'AA' ],
	'Shangri-La':                     [ 'Shangri-La', 'Super Rare', 'Eagle Union', 'Aircraft Carrier', 0.5, 'F*', 'TB*', 'DB*' ],
	'Independence':                   [ 'Independence', 'Elite', 'Eagle Union', 'Light Aircraft Carrier', 1.5, 'F*', 'TB*', 'AA' ],
	'Princeton':                      [ 'Princeton', 'Elite', 'Eagle Union', 'Light Aircraft Carrier', 2, 'F*', 'TB*', 'AA' ],
	'Albacore':                       [ 'Albacore', 'Super Rare', 'Eagle Union', 'Submarine', 1, 'T', 'T', 'DD' ],
	'Bluegill':                       [ 'Bluegill', 'Elite', 'Eagle Union', 'Submarine', 1.5, 'T', 'T', 'DD' ],
	'Cavalla':                        [ 'Cavalla', 'Super Rare', 'Eagle Union', 'Submarine', 1, 'T', 'T', 'DD' ],
	'Dace':                           [ 'Dace', 'Elite', 'Eagle Union', 'Submarine', 1.5, 'T', 'T', 'DD' ],
	'Albacore_µ':                     [ 'Albacore µ', 'Elite', 'Eagle Union', 'Submarine', 1, 'T', 'T', 'DD' ],
	'Vestal':                         [ 'Vestal', 'Elite', 'Eagle Union', 'Repair Ship', 0, 'A', 'AA', 'AA' ],
	'Vampire':                        [ 'Vampire', 'Elite', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Amazon':                         [ 'Amazon', 'Elite', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Acasta':                         [ 'Acasta', 'Elite', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Ardent':                         [ 'Ardent', 'Elite', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Beagle':                         [ 'Beagle', 'Normal', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Bulldog':                        [ 'Bulldog', 'Normal', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Comet':                          [ 'Comet', 'Rare', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Crescent':                       [ 'Crescent', 'Rare', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Cygnet':                         [ 'Cygnet', 'Rare', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Echo':                           [ 'Echo', 'Rare', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Foxhound':                       [ 'Foxhound', 'Rare', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Fortune':                        [ 'Fortune', 'Elite', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Grenville':                      [ 'Grenville', 'Elite', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Glowworm':                       [ 'Glowworm', 'Elite', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Hardy':                          [ 'Hardy', 'Elite', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Hunter':                         [ 'Hunter', 'Rare', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Icarus':                         [ 'Icarus', 'Elite', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Javelin':                        [ 'Javelin', 'Super Rare', 'Royal Navy', 'Destroyer', 0.5, 'DD*', 'T', 'AA' ],
	'Juno':                           [ 'Juno', 'Rare', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Jupiter':                        [ 'Jupiter', 'Rare', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Jersey':                         [ 'Jersey', 'Rare', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Matchless':                      [ 'Matchless', 'Elite', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Musketeer':                      [ 'Musketeer', 'Elite', 'Royal Navy', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Eskimo':                         [ 'Eskimo', 'Elite', 'Royal Navy', 'Destroyer', 1.5, 'DD', 'T', 'AA' ],
	'Curacoa':                        [ 'Curacoa', 'Elite', 'Royal Navy', 'Light Cruiser', 1.5, 'CL', 'AA', 'AA' ],
	'Curlew':                         [ 'Curlew', 'Elite', 'Royal Navy', 'Light Cruiser', 1, 'CL', 'AA', 'AA' ],
	'Leander':                        [ 'Leander', 'Rare', 'Royal Navy', 'Light Cruiser', 2, 'CL', 'T', 'AA' ],
	'Achilles':                       [ 'Achilles', 'Elite', 'Royal Navy', 'Light Cruiser', 1.5, 'CL', 'T', 'AA' ],
	'Ajax':                           [ 'Ajax', 'Elite', 'Royal Navy', 'Light Cruiser', 1.5, 'CL', 'T', 'AA' ],
	'Arethusa':                       [ 'Arethusa', 'Rare', 'Royal Navy', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Galatea':                        [ 'Galatea', 'Rare', 'Royal Navy', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Penelope':                       [ 'Penelope', 'Elite', 'Royal Navy', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Aurora':                         [ 'Aurora', 'Elite', 'Royal Navy', 'Light Cruiser', 0.5, 'CL', 'T', 'AA' ],
	'Southampton':                    [ 'Southampton', 'Rare', 'Royal Navy', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Newcastle':                      [ 'Newcastle', 'Elite', 'Royal Navy', 'Light Cruiser', 1, 'CL', 'T', 'AA*' ],
	'Sheffield':                      [ 'Sheffield', 'Elite', 'Royal Navy', 'Light Cruiser', 1.5, 'CL', 'T', 'AA' ],
	'Glasgow':                        [ 'Glasgow', 'Rare', 'Royal Navy', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Gloucester':                     [ 'Gloucester', 'Elite', 'Royal Navy', 'Light Cruiser', 2, 'CL', 'T', 'AA' ],
	'Edinburgh':                      [ 'Edinburgh', 'Elite', 'Royal Navy', 'Light Cruiser', 2, 'CL', 'T', 'AA' ],
	'Belfast':                        [ 'Belfast', 'Super Rare', 'Royal Navy', 'Light Cruiser', 1.5, 'CL', 'T', 'AA' ],
	'Little_Bel':                     [ 'Little Bel', 'Elite', 'Royal Navy', 'Light Cruiser', 1.5, 'CL', 'T', 'AA' ],
	'Sheffield_µ':                    [ 'Sheffield µ', 'Elite', 'Royal Navy', 'Light Cruiser', 1.5, 'CL*', 'T', 'AA' ],
	'Dido':                           [ 'Dido', 'Super Rare', 'Royal Navy', 'Light Cruiser', 1, 'CL/DD', 'T', 'AA' ],
	'Hermione':                       [ 'Hermione', 'Super Rare', 'Royal Navy', 'Light Cruiser', 2, 'CL/DD', 'T', 'AA' ],
	'Sirius':                         [ 'Sirius', 'Super Rare', 'Royal Navy', 'Light Cruiser', 1, 'CL/DD', 'T', 'AA' ],
	'Black_Prince':                   [ 'Black Prince', 'Elite', 'Royal Navy', 'Light Cruiser', 2, 'CL/DD', 'T', 'AA' ],
	'Dido_µ':                         [ 'Dido µ', 'Super Rare', 'Royal Navy', 'Light Cruiser', 1, 'CL/DD', 'T', 'AA' ],
	'Fiji':                           [ 'Fiji', 'Rare', 'Royal Navy', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Jamaica':                        [ 'Jamaica', 'Rare', 'Royal Navy', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Swiftsure':                      [ 'Swiftsure', 'Super Rare', 'Royal Navy', 'Light Cruiser', 0.5, 'CL', 'T', 'AA' ],
	'London':                         [ 'London', 'Super Rare', 'Royal Navy', 'Heavy Cruiser', 0.5, 'CA*', 'T/DD', 'AA' ],
	'Shropshire':                     [ 'Shropshire', 'Rare', 'Royal Navy', 'Heavy Cruiser', 3, 'CA*', 'T', 'AA' ],
	'Kent':                           [ 'Kent', 'Rare', 'Royal Navy', 'Heavy Cruiser', 3, 'CA', 'T', 'AA' ],
	'Suffolk':                        [ 'Suffolk', 'Elite', 'Royal Navy', 'Heavy Cruiser', 2, 'CA*', 'T', 'AA' ],
	'Norfolk':                        [ 'Norfolk', 'Rare', 'Royal Navy', 'Heavy Cruiser', 3, 'CA', 'T', 'AA' ],
	'Dorsetshire':                    [ 'Dorsetshire', 'Elite', 'Royal Navy', 'Heavy Cruiser', 3, 'CA', 'T', 'AA' ],
	'York':                           [ 'York', 'Super Rare', 'Royal Navy', 'Heavy Cruiser', 2, 'CA*', 'T*', 'AA*' ],
	'Exeter':                         [ 'Exeter', 'Super Rare', 'Royal Navy', 'Heavy Cruiser', 2, 'CA*', 'T', 'AA' ],
	'Sussex':                         [ 'Sussex', 'Rare', 'Royal Navy', 'Heavy Cruiser', 3, 'CA*', 'T', 'AA' ],
	'Renown':                         [ 'Renown', 'Elite', 'Royal Navy', 'Battlecruiser', 3, 'BB*', 'DD', 'AA' ],
	'Repulse':                        [ 'Repulse', 'Rare', 'Royal Navy', 'Battlecruiser', 3, 'BB', 'DD', 'AA' ],
	'Little_Renown':                  [ 'Little Renown', 'Elite', 'Royal Navy', 'Battlecruiser', 1.5, 'BB', 'DD', 'AA' ],
	'Hood':                           [ 'Hood', 'Super Rare', 'Royal Navy', 'Battlecruiser', 1, 'BB*', 'DD', 'AA' ],
	'Queen_Elizabeth':                [ 'Queen Elizabeth', 'Elite', 'Royal Navy', 'Battleship', 1, 'BB', 'CL/DD', 'AA' ],
	'Warspite':                       [ 'Warspite', 'Ultra Rare', 'Royal Navy', 'Battleship', 0, 'BB', 'CL/DD', 'AA' ],
	'Valiant':                        [ 'Valiant', 'Elite', 'Royal Navy', 'Battleship', 2, 'BB*', 'CL/DD', 'AA' ],
	'Nelson':                         [ 'Nelson', 'Elite', 'Royal Navy', 'Battleship', 3, 'BB*', 'CL/DD', 'AA' ],
	'Rodney':                         [ 'Rodney', 'Elite', 'Royal Navy', 'Battleship', 3, 'BB*', 'CL/DD', 'AA' ],
	'King_George_V':                  [ 'King George V', 'Super Rare', 'Royal Navy', 'Battleship', 1, 'BB', 'CL/DD', 'AA' ],
	'Prince_of_Wales':                [ 'Prince of Wales', 'Super Rare', 'Royal Navy', 'Battleship', 1, 'BB', 'CL/DD', 'AA' ],
	'Duke_of_York':                   [ 'Duke of York', 'Super Rare', 'Royal Navy', 'Battleship', 0.5, 'BB', 'CL/DD', 'AA' ],
	'Howe':                           [ 'Howe', 'Super Rare', 'Royal Navy', 'Battleship', 0, 'BB', 'CL/DD', 'AA' ],
	'Hermes':                         [ 'Hermes', 'Rare', 'Royal Navy', 'Light Aircraft Carrier', 1.5, 'TB*', 'TB*', 'AA' ],
	'Unicorn':                        [ 'Unicorn', 'Elite', 'Royal Navy', 'Light Aircraft Carrier', 0.5, 'F*', 'TB*', 'AA' ],
	'Chaser':                         [ 'Chaser', 'Elite', 'Royal Navy', 'Light Aircraft Carrier', 2, 'F*', 'TB*', 'AA' ],
	'Perseus':                        [ 'Perseus', 'Super Rare', 'Royal Navy', 'Light Aircraft Carrier', 0, 'F*', 'TB*', 'AA' ],
	'Centaur':                        [ 'Centaur', 'Super Rare', 'Royal Navy', 'Light Aircraft Carrier', 0, 'F*', 'F*', 'TB*' ],
	'Eagle':                          [ 'Eagle', 'Elite', 'Royal Navy', 'Aircraft Carrier', 1.5, 'F*', 'TB*', 'CL/DB*' ],
	'Ark_Royal':                      [ 'Ark Royal', 'Elite', 'Royal Navy', 'Aircraft Carrier', 1, 'TB*', 'TB*', 'DB*' ],
	'Illustrious':                    [ 'Illustrious', 'Super Rare', 'Royal Navy', 'Aircraft Carrier', 0.5, 'F*', 'F*', 'TB*' ],
	'Victorious':                     [ 'Victorious', 'Super Rare', 'Royal Navy', 'Aircraft Carrier', 2, 'F*', 'DB*', 'TB*' ],
	'Formidable':                     [ 'Formidable', 'Super Rare', 'Royal Navy', 'Aircraft Carrier', 0, 'DB*', 'TB*', 'TB*' ],
	'Glorious':                       [ 'Glorious', 'Elite', 'Royal Navy', 'Aircraft Carrier', 3, 'F*', 'TB*', 'TB*' ],
	'Little_Illustrious':             [ 'Little Illustrious', 'Elite', 'Royal Navy', 'Aircraft Carrier', 3, 'F*', 'F*', 'TB*' ],
	'Illustrious_µ':                  [ 'Illustrious µ', 'Super Rare', 'Royal Navy', 'Aircraft Carrier', 0.5, 'F*', 'F*', 'TB*' ],
	'Erebus':                         [ 'Erebus', 'Elite', 'Royal Navy', 'Monitor', 2, 'BB', 'DD', 'AA' ],
	'Terror':                         [ 'Terror', 'Elite', 'Royal Navy', 'Monitor', 3, 'BB', 'DD', 'AA' ],
	'Abercrombie':                    [ 'Abercrombie', 'Elite', 'Royal Navy', 'Monitor', 3, 'BB', 'DD', 'AA' ],
	'Kamikaze':                       [ 'Kamikaze', 'Elite', 'Sakura Empire', 'Destroyer', 3, 'DD*', 'T*', 'AA' ],
	'Matsukaze':                      [ 'Matsukaze', 'Elite', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Hatakaze':                       [ 'Hatakaze', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Mutsuki':                        [ 'Mutsuki', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Kisaragi':                       [ 'Kisaragi', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T*', 'AA' ],
	'Uzuki':                          [ 'Uzuki', 'Normal', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Minazuki':                       [ 'Minazuki', 'Normal', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Fumizuki':                       [ 'Fumizuki', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Nagatsuki':                      [ 'Nagatsuki', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Mikazuki':                       [ 'Mikazuki', 'Normal', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Fubuki':                         [ 'Fubuki', 'Elite', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Uranami':                        [ 'Uranami', 'Elite', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Ayanami':                        [ 'Ayanami', 'Super Rare', 'Sakura Empire', 'Destroyer', 0, 'DD*', 'T', 'AA' ],
	'Akatsuki':                       [ 'Akatsuki', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Hibiki':                         [ 'Hibiki', 'Elite', 'Sakura Empire', 'Destroyer', 2, 'DD', 'T*', 'AA' ],
	'Ikazuchi':                       [ 'Ikazuchi', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Inazuma':                        [ 'Inazuma', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Hatsuharu':                      [ 'Hatsuharu', 'Elite', 'Sakura Empire', 'Destroyer', 1.5, 'DD', 'T*', 'AA' ],
	'Wakaba':                         [ 'Wakaba', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T*', 'AA' ],
	'Hatsushimo':                     [ 'Hatsushimo', 'Elite', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T*', 'AA' ],
	'Ariake':                         [ 'Ariake', 'Elite', 'Sakura Empire', 'Destroyer', 1.5, 'DD', 'T*', 'AA' ],
	'Yuugure':                        [ 'Yuugure', 'Elite', 'Sakura Empire', 'Destroyer', 2, 'DD', 'T', 'AA' ],
	'Shiratsuyu':                     [ 'Shiratsuyu', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Shigure':                        [ 'Shigure', 'Super Rare', 'Sakura Empire', 'Destroyer', 1, 'DD*', 'T', 'AA' ],
	'Yuudachi':                       [ 'Yuudachi', 'Super Rare', 'Sakura Empire', 'Destroyer', 1, 'DD*', 'T', 'AA' ],
	'Kawakaze':                       [ 'Kawakaze', 'Super Rare', 'Sakura Empire', 'Destroyer', 1, 'DD', 'T', 'AA' ],
	'Asashio':                        [ 'Asashio', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Ooshio':                         [ 'Ooshio', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Michishio':                      [ 'Michishio', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Arashio':                        [ 'Arashio', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Kasumi':                         [ 'Kasumi', 'Elite', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Kagerou':                        [ 'Kagerou', 'Elite', 'Sakura Empire', 'Destroyer', 1, 'DD', 'T*', 'AA' ],
	'Shiranui':                       [ 'Shiranui', 'Rare', 'Sakura Empire', 'Destroyer', 2, 'DD', 'T*', 'AA' ],
	'Kuroshio':                       [ 'Kuroshio', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T*', 'AA' ],
	'Oyashio':                        [ 'Oyashio', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T*', 'AA' ],
	'Yukikaze':                       [ 'Yukikaze', 'Super Rare', 'Sakura Empire', 'Destroyer', 0.5, 'DD', 'T', 'AA' ],
	'Urakaze':                        [ 'Urakaze', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Isokaze':                        [ 'Isokaze', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Hamakaze':                       [ 'Hamakaze', 'Elite', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Tanikaze':                       [ 'Tanikaze', 'Elite', 'Sakura Empire', 'Destroyer', 2, 'DD', 'T', 'AA' ],
	'Nowaki':                         [ 'Nowaki', 'Elite', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Makinami':                       [ 'Makinami', 'Elite', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T*', 'AA' ],
	'Kiyonami':                       [ 'Kiyonami', 'Rare', 'Sakura Empire', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Naganami':                       [ 'Naganami', 'Elite', 'Sakura Empire', 'Destroyer', 1, 'DD', 'T', 'AA' ],
	'Suzutsuki':                      [ 'Suzutsuki', 'Super Rare', 'Sakura Empire', 'Destroyer', 0, 'DD', 'T', 'AA' ],
	'Niizuki':                        [ 'Niizuki', 'Elite', 'Sakura Empire', 'Destroyer', 2, 'DD', 'T', 'AA*' ],
	'Harutsuki':                      [ 'Harutsuki', 'Elite', 'Sakura Empire', 'Destroyer', 1, 'DD', 'T', 'AA' ],
	'Yoizuki':                        [ 'Yoizuki', 'Elite', 'Sakura Empire', 'Destroyer', 1, 'DD', 'T', 'AA' ],
	'Hanazuki':                       [ 'Hanazuki', 'Elite', 'Sakura Empire', 'Destroyer', 1, 'DD', 'T', 'AA' ],
	'Nagara':                         [ 'Nagara', 'Normal', 'Sakura Empire', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Isuzu':                          [ 'Isuzu', 'Elite', 'Sakura Empire', 'Light Cruiser', 1, 'CL', 'T', 'AA*' ],
	'Kinu':                           [ 'Kinu', 'Super Rare', 'Sakura Empire', 'Light Cruiser', 1.5, 'CL', 'T', 'AA' ],
	'Abukuma':                        [ 'Abukuma', 'Rare', 'Sakura Empire', 'Light Cruiser', 3, 'CL', 'T*', 'AA' ],
	'Yuubari':                        [ 'Yuubari', 'Super Rare', 'Sakura Empire', 'Light Cruiser', 2, 'CL', 'T', 'AA' ],
	'Sendai':                         [ 'Sendai', 'Elite', 'Sakura Empire', 'Light Cruiser', 1.5, 'CL', 'T', 'AA' ],
	'Jintsuu':                        [ 'Jintsuu', 'Super Rare', 'Sakura Empire', 'Light Cruiser', 0.5, 'CL', 'T', 'AA' ],
	'Naka':                           [ 'Naka', 'Rare', 'Sakura Empire', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Mogami':                         [ 'Mogami', 'Super Rare', 'Sakura Empire', 'Heavy Cruiser', 1, 'CA', 'T*', 'AA' ],
	'Mikuma':                         [ 'Mikuma', 'Elite', 'Sakura Empire', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Agano':                          [ 'Agano', 'Elite', 'Sakura Empire', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Noshiro':                        [ 'Noshiro', 'Super Rare', 'Sakura Empire', 'Light Cruiser', 0, 'CL', 'T', 'AA' ],
	'Furutaka':                       [ 'Furutaka', 'Rare', 'Sakura Empire', 'Heavy Cruiser', 3, 'CA', 'T*', 'AA' ],
	'Kako':                           [ 'Kako', 'Rare', 'Sakura Empire', 'Heavy Cruiser', 3, 'CA', 'T*', 'AA' ],
	'Aoba':                           [ 'Aoba', 'Normal', 'Sakura Empire', 'Heavy Cruiser', 3, 'CA', 'T', 'AA' ],
	'Kinugasa':                       [ 'Kinugasa', 'Normal', 'Sakura Empire', 'Heavy Cruiser', 3, 'CA', 'T', 'AA' ],
	'Myoukou':                        [ 'Myoukou', 'Rare', 'Sakura Empire', 'Heavy Cruiser', 2, 'CA', 'T', 'AA' ],
	'Nachi':                          [ 'Nachi', 'Rare', 'Sakura Empire', 'Heavy Cruiser', 2, 'CA', 'T', 'AA' ],
	'Ashigara':                       [ 'Ashigara', 'Elite', 'Sakura Empire', 'Heavy Cruiser', 3, 'CA', 'T', 'AA' ],
	'Takao':                          [ 'Takao', 'Super Rare', 'Sakura Empire', 'Heavy Cruiser', 1, 'CA*', 'T*', 'AA' ],
	'Atago':                          [ 'Atago', 'Super Rare', 'Sakura Empire', 'Heavy Cruiser', 1, 'CA', 'T*', 'AA' ],
	'Maya':                           [ 'Maya', 'Super Rare', 'Sakura Empire', 'Heavy Cruiser', 1.5, 'CA', 'T', 'AA' ],
	'Choukai':                        [ 'Choukai', 'Super Rare', 'Sakura Empire', 'Heavy Cruiser', 1.5, 'CA*', 'T', 'AA' ],
	'Suzuya':                         [ 'Suzuya', 'Elite', 'Sakura Empire', 'Heavy Cruiser', 2, 'CA/CL*', 'T', 'AA' ],
	'Kumano':                         [ 'Kumano', 'Elite', 'Sakura Empire', 'Heavy Cruiser', 2, 'CA/CL', 'T', 'AA' ],
	'Kongou':                         [ 'Kongou', 'Elite', 'Sakura Empire', 'Battlecruiser', 3, 'BB', 'CL/DD', 'AA' ],
	'Hiei':                           [ 'Hiei', 'Elite', 'Sakura Empire', 'Battlecruiser', 3, 'BB', 'CL/DD', 'AA' ],
	'Haruna':                         [ 'Haruna', 'Elite', 'Sakura Empire', 'Battlecruiser', 3, 'BB*', 'CL/DD', 'AA' ],
	'Kirishima':                      [ 'Kirishima', 'Elite', 'Sakura Empire', 'Battlecruiser', 3, 'BB', 'CL/DD', 'AA' ],
	'Hiei-chan':                      [ 'Hiei-chan', 'Elite', 'Sakura Empire', 'Battlecruiser', 3, 'BB', 'CL/DD', 'AA' ],
	'Amagi':                          [ 'Amagi', 'Super Rare', 'Sakura Empire', 'Battlecruiser', 0.5, 'BB*', 'CL/DD', 'AA' ],
	'Mikasa':                         [ 'Mikasa', 'Super Rare', 'Sakura Empire', 'Battleship', 2, 'BB*', 'CL/DD', 'DD' ],
	'Fusou':                          [ 'Fusou', 'Elite', 'Sakura Empire', 'Aviation Battleship', 2, 'BB', 'S', 'AA' ],
	'Yamashiro':                      [ 'Yamashiro', 'Elite', 'Sakura Empire', 'Aviation Battleship', 2, 'BB', 'S', 'AA' ],
	'Ise':                            [ 'Ise', 'Elite', 'Sakura Empire', 'Aviation Battleship', 1.5, 'BB', 'S', 'AA' ],
	'Hyuuga':                         [ 'Hyuuga', 'Elite', 'Sakura Empire', 'Aviation Battleship', 1, 'BB', 'S', 'AA' ],
	'Nagato':                         [ 'Nagato', 'Super Rare', 'Sakura Empire', 'Battleship', 0.5, 'BB*', 'CL/DD', 'AA' ],
	'Mutsu':                          [ 'Mutsu', 'Elite', 'Sakura Empire', 'Battleship', 2, 'BB*', 'CL/DD', 'AA' ],
	'Kaga_(Battleship)':              [ 'Kaga (Battleship)', 'Super Rare', 'Sakura Empire', 'Battleship', 1, 'BB*', 'CL/DD', 'AA' ],
	'Tosa':                           [ 'Tosa', 'Super Rare', 'Sakura Empire', 'Battleship', 0.5, 'BB*', 'CL/DD', 'AA' ],
	'Kii':                            [ 'Kii', 'Super Rare', 'Sakura Empire', 'Battleship', 0.5, 'BB', 'CL/DD', 'AA' ],
	'Suruga':                         [ 'Suruga', 'Super Rare', 'Sakura Empire', 'Battleship', 1, 'BB', 'CL/DD', 'AA' ],
	'Hiyou':                          [ 'Hiyou', 'Rare', 'Sakura Empire', 'Light Aircraft Carrier', 3, 'F', 'DB', 'TB' ],
	'Junyou':                         [ 'Junyou', 'Rare', 'Sakura Empire', 'Light Aircraft Carrier', 3, 'F', 'DB', 'TB' ],
	'Houshou':                        [ 'Houshou', 'Elite', 'Sakura Empire', 'Light Aircraft Carrier', 3, 'CL', 'F*', 'TB*' ],
	'Shouhou':                        [ 'Shouhou', 'Elite', 'Sakura Empire', 'Light Aircraft Carrier', 0.5, 'DB*', 'TB*', 'AA' ],
	'Ryuujou':                        [ 'Ryuujou', 'Elite', 'Sakura Empire', 'Light Aircraft Carrier', 2, 'F*', 'TB*', 'AA' ],
	'Ryuuhou':                        [ 'Ryuuhou', 'Super Rare', 'Sakura Empire', 'Light Aircraft Carrier', 0, 'F*', 'TB*', 'AA' ],
	'Chitose':                        [ 'Chitose', 'Elite', 'Sakura Empire', 'Light Aircraft Carrier', 2, 'F*', 'TB*', 'AA' ],
	'Chiyoda':                        [ 'Chiyoda', 'Elite', 'Sakura Empire', 'Light Aircraft Carrier', 2, 'F*', 'TB*', 'AA' ],
	'Akagi':                          [ 'Akagi', 'Super Rare', 'Sakura Empire', 'Aircraft Carrier', 1, 'F', 'DB', 'TB' ],
	'Kaga':                           [ 'Kaga', 'Super Rare', 'Sakura Empire', 'Aircraft Carrier', 1, 'F', 'DB', 'TB' ],
	'Akagi-chan':                     [ 'Akagi-chan', 'Elite', 'Sakura Empire', 'Aircraft Carrier', 3, 'F*', 'DB*', 'TB*' ],
	'Akagi_µ':                        [ 'Akagi µ', 'Super Rare', 'Sakura Empire', 'Aircraft Carrier', 0.5, 'F', 'DB', 'TB' ],
	'Souryuu':                        [ 'Souryuu', 'Super Rare', 'Sakura Empire', 'Aircraft Carrier', 1, 'F*', 'DB*', 'TB*' ],
	'Hiryuu':                         [ 'Hiryuu', 'Super Rare', 'Sakura Empire', 'Aircraft Carrier', 1, 'F', 'DB', 'TB' ],
	'Shoukaku':                       [ 'Shoukaku', 'Super Rare', 'Sakura Empire', 'Aircraft Carrier', 0.5, 'F*', 'DB*', 'TB*' ],
	'Zuikaku':                        [ 'Zuikaku', 'Super Rare', 'Sakura Empire', 'Aircraft Carrier', 0.5, 'F*', 'DB*', 'TB*' ],
	'Taihou':                         [ 'Taihou', 'Super Rare', 'Sakura Empire', 'Aircraft Carrier', 1, 'F*', 'DB*', 'TB*' ],
	'Taihou_µ':                       [ 'Taihou µ', 'Super Rare', 'Sakura Empire', 'Aircraft Carrier', 1, 'F*', 'DB*', 'TB*' ],
	'Shinano':                        [ 'Shinano', 'Ultra Rare', 'Sakura Empire', 'Aircraft Carrier', 0, 'F/DB/TB*', 'DB*', 'TB*' ],
	'I-19':                           [ 'I-19', 'Super Rare', 'Sakura Empire', 'Submarine', 1, 'T', 'T', 'DD' ],
	'I-25':                           [ 'I-25', 'Elite', 'Sakura Empire', 'Submarine', 1.5, 'T', 'T', 'DD' ],
	'I-26':                           [ 'I-26', 'Elite', 'Sakura Empire', 'Submarine', 2, 'T', 'T', 'DD' ],
	'I-56':                           [ 'I-56', 'Elite', 'Sakura Empire', 'Submarine', 1.5, 'T', 'T', 'DD' ],
	'I-58':                           [ 'I-58', 'Elite', 'Sakura Empire', 'Submarine', 1.5, 'T', 'T', 'DD' ],
	'I-168':                          [ 'I-168', 'Super Rare', 'Sakura Empire', 'Submarine', 1, 'T', 'T', 'DD' ],
	'I-13':                           [ 'I-13', 'Super Rare', 'Sakura Empire', 'Submarine Carrier', 0.5, 'T', 'T', 'S' ],
	'Akashi':                         [ 'Akashi', 'Super Rare', 'Sakura Empire', 'Repair Ship', 0, 'A', 'AA', 'AA' ],
	'Kashino':                        [ 'Kashino', 'Elite', 'Sakura Empire', 'Munition Ship', 1.5, 'DD', 'AA', 'A' ],
	'Z1':                             [ 'Z1', 'Super Rare', 'Ironblood', 'Destroyer', 1, 'DD', 'T', 'AA' ],
	'Z2':                             [ 'Z2', 'Elite', 'Ironblood', 'Destroyer', 3, 'DD*', 'T', 'AA' ],
	'Z18':                            [ 'Z18', 'Rare', 'Ironblood', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Z19':                            [ 'Z19', 'Rare', 'Ironblood', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Z20':                            [ 'Z20', 'Normal', 'Ironblood', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Z21':                            [ 'Z21', 'Normal', 'Ironblood', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Z23':                            [ 'Z23', 'Super Rare', 'Ironblood', 'Destroyer', 0.5, 'CL/DD*', 'T', 'AA' ],
	'Z24':                            [ 'Z24', 'Elite', 'Ironblood', 'Destroyer', 1, 'CL/DD', 'T', 'AA' ],
	'Z25':                            [ 'Z25', 'Elite', 'Ironblood', 'Destroyer', 2, 'CL/DD', 'T', 'AA' ],
	'Z26':                            [ 'Z26', 'Elite', 'Ironblood', 'Destroyer', 2, 'CL/DD', 'T', 'AA' ],
	'Z28':                            [ 'Z28', 'Elite', 'Ironblood', 'Destroyer', 1, 'CL/DD', 'T', 'AA' ],
	'Z35':                            [ 'Z35', 'Elite', 'Ironblood', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Z36':                            [ 'Z36', 'Elite', 'Ironblood', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Z46':                            [ 'Z46', 'Super Rare', 'Ironblood', 'Destroyer', 0.5, 'DD', 'T', 'AA' ],
	'Konigsberg':                     [ 'Königsberg', 'Normal', 'Ironblood', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Karlsruhe':                      [ 'Karlsruhe', 'Rare', 'Ironblood', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Koln':                           [ 'Köln', 'Rare', 'Ironblood', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Leipzig':                        [ 'Leipzig', 'Elite', 'Ironblood', 'Light Cruiser', 1, 'CL', 'T', 'AA' ],
	'Nurnberg':                       [ 'Nürnberg', 'Elite', 'Ironblood', 'Light Cruiser', 1.5, 'CL', 'T', 'AA' ],
	'Deutschland':                    [ 'Deutschland', 'Elite', 'Ironblood', 'Heavy Cruiser', 1.5, 'CA', 'T', 'AA' ],
	'Admiral_Graf_Spee':              [ 'Admiral Graf Spee', 'Elite', 'Ironblood', 'Heavy Cruiser', 1.5, 'CA', 'T', 'AA' ],
	'Admiral_Hipper':                 [ 'Admiral Hipper', 'Elite', 'Ironblood', 'Heavy Cruiser', 2, 'CA', 'T', 'AA' ],
	'Prinz_Eugen':                    [ 'Prinz Eugen', 'Super Rare', 'Ironblood', 'Heavy Cruiser', 1.5, 'CA', 'T', 'AA' ],
	'Admiral_Hipper_µ':               [ 'Admiral Hipper µ', 'Elite', 'Ironblood', 'Heavy Cruiser', 2, 'CA', 'T', 'AA' ],
	'Roon_µ':                         [ 'Roon µ', 'Super Rare', 'Ironblood', 'Heavy Cruiser', 0, 'CA', 'T', 'AA' ],
	'Prinz_Heinrich':                 [ 'Prinz Heinrich', 'Super Rare', 'Ironblood', 'Heavy Cruiser', 0, 'CA/CB', 'T', 'AA' ],
	'Scharnhorst':                    [ 'Scharnhorst', 'Elite', 'Ironblood', 'Battlecruiser', 3, 'BB', 'CL/DD', 'AA' ],
	'Gneisenau':                      [ 'Gneisenau', 'Elite', 'Ironblood', 'Battlecruiser', 3, 'BB', 'CL/DD', 'AA' ],
	'Bismarck':                       [ 'Bismarck', 'Super Rare', 'Ironblood', 'Battleship', 1, 'BB*', 'CL/DD', 'AA' ],
	'Tirpitz':                        [ 'Tirpitz', 'Super Rare', 'Ironblood', 'Battleship', 1.5, 'BB', 'CL/DD', 'AA' ],
	'Weser':                          [ 'Weser', 'Elite', 'Ironblood', 'Light Aircraft Carrier', 2, 'F*', 'DB*', 'AA' ],
	'Graf_Zeppelin':                  [ 'Graf Zeppelin', 'Super Rare', 'Ironblood', 'Aircraft Carrier', 0.5, 'F', 'DB', 'DB/TB' ],
	'Peter_Strasser':                 [ 'Peter Strasser', 'Super Rare', 'Ironblood', 'Aircraft Carrier', 1, 'F*', 'DB*', 'TB*' ],
	'Zeppy':                          [ 'Zeppy', 'Elite', 'Ironblood', 'Aircraft Carrier', 2, 'F', 'DB', 'CL/DB' ],
	'U-37':                           [ 'U-37', 'Super Rare', 'Ironblood', 'Submarine', 0, 'T', 'T', 'DD' ],
	'U-47':                           [ 'U-47', 'Super Rare', 'Ironblood', 'Submarine', 0, 'T', 'T', 'DD' ],
	'U-73':                           [ 'U-73', 'Elite', 'Ironblood', 'Submarine', 1.5, 'T', 'T', 'DD' ],
	'U-81':                           [ 'U-81', 'Super Rare', 'Ironblood', 'Submarine', 0, 'T', 'T', 'DD' ],
	'U-96':                           [ 'U-96', 'Super Rare', 'Ironblood', 'Submarine', 0, 'T', 'T', 'DD' ],
	'U-101':                          [ 'U-101', 'Super Rare', 'Ironblood', 'Submarine', 0.5, 'T', 'T', 'DD' ],
	'U-110':                          [ 'U-110', 'Elite', 'Ironblood', 'Submarine', 1.5, 'T', 'T', 'DD' ],
	'U-410':                          [ 'U-410', 'Elite', 'Ironblood', 'Submarine', 1, 'T', 'T', 'DD' ],
	'U-522':                          [ 'U-522', 'Elite', 'Ironblood', 'Submarine', 1, 'T', 'T', 'DD' ],
	'U-556':                          [ 'U-556', 'Elite', 'Ironblood', 'Submarine', 1.5, 'T', 'T', 'DD' ],
	'U-557':                          [ 'U-557', 'Elite', 'Ironblood', 'Submarine', 2, 'T', 'T', 'DD' ],
	'An_Shan':                        [ 'An Shan', 'Elite', 'Dragon Empery', 'Destroyer', 1.5, 'DD', 'T', 'AA' ],
	'Fu_Shun':                        [ 'Fu Shun', 'Elite', 'Dragon Empery', 'Destroyer', 1, 'DD', 'T', 'AA' ],
	'Chang_Chun':                     [ 'Chang Chun', 'Elite', 'Dragon Empery', 'Destroyer', 1.5, 'DD', 'T', 'AA' ],
	'Tai_Yuan':                       [ 'Tai Yuan', 'Elite', 'Dragon Empery', 'Destroyer', 1.5, 'DD', 'T', 'AA' ],
	'Ying_Swei':                      [ 'Ying Swei', 'Elite', 'Dragon Empery', 'Light Cruiser', 2, 'CL', 'DD', 'T' ],
	'Chao_Ho':                        [ 'Chao Ho', 'Elite', 'Dragon Empery', 'Light Cruiser', 2, 'CL', 'DD', 'T' ],
	'Yat_Sen':                        [ 'Yat Sen', 'Elite', 'Dragon Empery', 'Light Cruiser', 1, 'CL', 'CL', 'AA' ],
	'Ning_Hai':                       [ 'Ning Hai', 'Super Rare', 'Dragon Empery', 'Light Cruiser', 1, 'CL', 'T', 'AA' ],
	'Ping_Hai':                       [ 'Ping Hai', 'Super Rare', 'Dragon Empery', 'Light Cruiser', 1, 'CL', 'T', 'AA' ],
	'Carabiniere':                    [ 'Carabiniere', 'Elite', 'Sardegna Empire', 'Destroyer', 2, 'DD', 'T', 'AA' ],
	'Vincenzo_Gioberti':              [ 'Vincenzo Gioberti', 'Elite', 'Sardegna Empire', 'Destroyer', 2, 'DD', 'T', 'AA' ],
	'Trento':                         [ 'Trento', 'Rare', 'Sardegna Empire', 'Heavy Cruiser', 3, 'CA', 'T', 'AA' ],
	'Zara':                           [ 'Zara', 'Super Rare', 'Sardegna Empire', 'Heavy Cruiser', 1, 'CA*', 'DD', 'AA' ],
	'Pola':                           [ 'Pola', 'Super Rare', 'Sardegna Empire', 'Heavy Cruiser', 0.5, 'CA*', 'DD', 'AA' ],
	'Littorio':                       [ 'Littorio', 'Super Rare', 'Sardegna Empire', 'Battleship', 1.5, 'BB*', 'CL/DD', 'AA' ],
	'Conte_di_Cavour':                [ 'Conte di Cavour', 'Rare', 'Sardegna Empire', 'Battleship', 3, 'BB', 'DD', 'AA' ],
	'Giulio_Cesare':                  [ 'Giulio Cesare', 'Elite', 'Sardegna Empire', 'Battleship', 3, 'BB*', 'DD', 'AA' ],
	'Gromky':                         [ 'Gromky', 'Elite', 'Northern Parliament', 'Destroyer', 1.5, 'DD', 'T', 'AA' ],
	'Gremyashchy':                    [ 'Gremyashchy', 'Elite', 'Northern Parliament', 'Destroyer', 1.5, 'DD', 'T', 'AA' ],
	'Grozny':                         [ 'Grozny', 'Elite', 'Northern Parliament', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Stremitelny':                    [ 'Stremitelny', 'Elite', 'Northern Parliament', 'Destroyer', 2, 'DD', 'T', 'AA' ],
	'Minsk':                          [ 'Minsk', 'Elite', 'Northern Parliament', 'Destroyer', 2, 'DD', 'T', 'AA' ],
	'Tashkent':                       [ 'Tashkent', 'Super Rare', 'Northern Parliament', 'Destroyer', 0, 'DD', 'T', 'AA' ],
	'Tashkent_µ':                     [ 'Tashkent µ', 'Super Rare', 'Northern Parliament', 'Destroyer', 0.5, 'DD', 'T', 'AA' ],
	'Avrora':                         [ 'Avrora', 'Super Rare', 'Northern Parliament', 'Light Cruiser', 1, 'CL', 'T', 'AA' ],
	'Pamiat_Merkuria':                [ 'Pamiat Merkuria', 'Super Rare', 'Northern Parliament', 'Light Cruiser', 0.5, 'DD', 'T', 'AA' ],
	'Murmansk':                       [ 'Murmansk', 'Elite', 'Northern Parliament', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Kirov':                          [ 'Kirov', 'Super Rare', 'Northern Parliament', 'Light Cruiser', 1, 'CL', 'T', 'AA' ],
	'Chapayev':                       [ 'Chapayev', 'Super Rare', 'Northern Parliament', 'Light Cruiser', 0.5, 'CL', 'DD', 'AA' ],
	'Tallinn':                        [ 'Tallinn', 'Super Rare', 'Northern Parliament', 'Heavy Cruiser', 0.5, 'CA/CL', 'T', 'AA' ],
	'Gangut':                         [ 'Gangut', 'Elite', 'Northern Parliament', 'Battleship', 1.5, 'BB*', 'CL/DD', 'AA' ],
	'Sovetskaya_Belorussiya':         [ 'Sovetskaya Belorussiya', 'Super Rare', 'Northern Parliament', 'Battleship', 0.5, 'BB*', 'CL/DD', 'AA' ],
	'Sovetskaya_Rossiya':             [ 'Sovetskaya Rossiya', 'Super Rare', 'Northern Parliament', 'Battleship', 1, 'BB*', 'CL/DD', 'AA' ],
	'Forbin':                         [ 'Forbin', 'Elite', 'Iris Libre', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Le_Temeraire':                   [ 'Le Temeraire', 'Elite', 'Iris Libre', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'L%27Opiniatre':                  [ 'L\'Opiniâtre', 'Elite', 'Iris Libre', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Le_Triomphant':                  [ 'Le Triomphant', 'Super Rare', 'Iris Libre', 'Destroyer', 1.5, 'DD*', 'T', 'AA' ],
	'Emile_Bertin':                   [ 'Émile Bertin', 'Super Rare', 'Iris Libre', 'Light Cruiser', 2, 'CL', 'T', 'AA' ],
	'Jeanne_d%27Arc':                 [ 'Jeanne d\'Arc', 'Super Rare', 'Iris Libre', 'Light Cruiser', 0.5, 'CL', 'T', 'AA' ],
	'Richelieu':                      [ 'Richelieu', 'Super Rare', 'Iris Libre', 'Battleship', 0, 'BB*', 'CL/DD', 'AA' ],
	'Bearn':                          [ 'Béarn', 'Elite', 'Iris Libre', 'Aircraft Carrier', 1.5, 'F*', 'TB*', 'CL/DB*' ],
	'Surcouf':                        [ 'Surcouf', 'Elite', 'Iris Libre', 'Submarine', 2, 'T', 'T', 'SS' ],
	'Le_Mars':                        [ 'Le Mars', 'Elite', 'Vichya Dominion', 'Destroyer', 2, 'DD', 'T', 'AA' ],
	'Tartu':                          [ 'Tartu', 'Elite', 'Vichya Dominion', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Le_Malin':                       [ 'Le Malin', 'Super Rare', 'Vichya Dominion', 'Destroyer', 1.5, 'DD*', 'T', 'AA' ],
	'Le_Malin_µ':                     [ 'Le Malin µ', 'Super Rare', 'Vichya Dominion', 'Destroyer', 0.5, 'DD', 'T', 'AA' ],
	'Vauquelin':                      [ 'Vauquelin', 'Elite', 'Vichya Dominion', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'La_Galissonniere':               [ 'La Galissonnière', 'Elite', 'Vichya Dominion', 'Light Cruiser', 3, 'CL*', 'T', 'AA' ],
	'Algerie':                        [ 'Algérie', 'Super Rare', 'Vichya Dominion', 'Heavy Cruiser', 1.5, 'CA', 'T', 'AA' ],
	'Dunkerque':                      [ 'Dunkerque', 'Elite', 'Vichya Dominion', 'Battlecruiser', 2, 'BB*', 'DD', 'AA' ],
	'Jean_Bart':                      [ 'Jean Bart', 'Super Rare', 'Vichya Dominion', 'Battleship', 1, 'BB', 'CL/DD', 'AA' ],
	'Gascogne_µ':                     [ 'Gascogne µ', 'Super Rare', 'Vichya Dominion', 'Battleship', 1, 'BB', 'CL/DD', 'AA' ],
	'HDN_Neptune':                    [ 'HDN Neptune', 'Elite', 'Neptunia', 'Light Cruiser', 3, 'CL', 'T', 'AA' ],
	'Noire':                          [ 'Noire', 'Elite', 'Neptunia', 'Heavy Cruiser', 3, 'CA', 'T', 'AA' ],
	'Blanc':                          [ 'Blanc', 'Elite', 'Neptunia', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Vert':                           [ 'Vert', 'Elite', 'Neptunia', 'Aircraft Carrier', 3, 'F', 'DB', 'DB' ],
	'Purple_Heart':                   [ 'Purple Heart', 'Super Rare', 'Neptunia', 'Light Cruiser', 3, 'CL*', 'T', 'AA' ],
	'Black_Heart':                    [ 'Black Heart', 'Super Rare', 'Neptunia', 'Heavy Cruiser', 3, 'CA', 'T', 'AA' ],
	'White_Heart':                    [ 'White Heart', 'Super Rare', 'Neptunia', 'Destroyer', 3, 'DD*', 'T', 'AA' ],
	'Green_Heart':                    [ 'Green Heart', 'Super Rare', 'Neptunia', 'Aircraft Carrier', 3, 'F', 'DB', 'DB' ],
	'Kizuna_AI':                      [ 'Kizuna AI', 'Elite', 'KizunaAI', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Elegant_Kizuna_AI':              [ 'Elegant Kizuna AI', 'Super Rare', 'KizunaAI', 'Heavy Cruiser', 1, 'CA', 'DD', 'AA' ],
	'Anniversary_Kizuna_AI':          [ 'Anniversary Kizuna AI', 'Super Rare', 'KizunaAI', 'Aircraft Carrier', 1.5, 'F*', 'DB*', 'TB*' ],
	'Super_Gamer_Kizuna_AI':          [ 'Super Gamer Kizuna AI', 'Super Rare', 'KizunaAI', 'Battleship', 2, 'BB', 'CL/DD', 'AA' ],
	'Shirakami_Fubuki':               [ 'Shirakami Fubuki', 'Super Rare', 'Hololive', 'Destroyer', 1, 'DD', 'T', 'DB' ],
	'Tokino_Sora':                    [ 'Tokino Sora', 'Super Rare', 'Hololive', 'Aircraft Carrier', 1, 'F*', 'DB*', 'TB*' ],
	'Minato_Aqua':                    [ 'Minato Aqua', 'Super Rare', 'Hololive', 'Submarine', 0.5, 'T', 'T', 'DD' ],
	'Natsuiro_Matsuri':               [ 'Natsuiro Matsuri', 'Elite', 'Hololive', 'Destroyer', 3, 'DD', 'T', 'AA' ],
	'Nakiri_Ayame':                   [ 'Nakiri Ayame', 'Elite', 'Hololive', 'Heavy Cruiser', 2, 'CA', 'DD', 'AA' ],
	'Murasaki_Shion':                 [ 'Murasaki Shion', 'Elite', 'Hololive', 'Light Aircraft Carrier', 3, 'F*', 'TB*', 'AA' ],
	'Ookami_Mio':                     [ 'Ookami Mio', 'Elite', 'Hololive', 'Aircraft Carrier', 1.5, 'F', 'DB', 'TB' ],
	'Marie_Rose':                     [ 'Marie Rose', 'Super Rare', 'Venus Vacation', 'Destroyer', 0.5, 'DD', 'T*', 'AA' ],
	'Honoka':                         [ 'Honoka', 'Super Rare', 'Venus Vacation', 'Battleship', 0.5, 'BB*', 'CL/DD', 'AA' ],
	'Kasumi_(DOA)':                   [ 'Kasumi (DOA)', 'Super Rare', 'Venus Vacation', 'Heavy Cruiser', 0.5, 'CA', 'T*', 'AA' ],
	'Misaki':                         [ 'Misaki', 'Super Rare', 'Venus Vacation', 'Light Cruiser', 0.5, 'CL', 'DD', 'AA' ],
	'Nagisa':                         [ 'Nagisa', 'Elite', 'Venus Vacation', 'Battleship', 1.5, 'BB*', 'CL/DD', 'AA' ],
	'Nyotengu':                       [ 'Nyotengu', 'Elite', 'Venus Vacation', 'Aircraft Carrier', 2, 'F*', 'DB*', 'TB*' ],
	'Monica':                         [ 'Monica', 'Elite', 'Venus Vacation', 'Light Cruiser', 2, 'CL', 'T', 'AA' ],
	'Hiryuu_META':                    [ 'Hiryuu META', 'Super Rare', 'META', 'Aircraft Carrier', 0, 'F', 'DB', 'TB' ],
	'HMS_Neptune':                    [ 'HMS Neptune', 'Priority', 'Royal Navy', 'Light Cruiser', 0.5, 'CL', 'T', 'AA' ],
	'Monarch':                        [ 'Monarch', 'Priority', 'Royal Navy', 'Battleship', 0, 'BB*', 'CL/DD', 'AA' ],
	'Ibuki':                          [ 'Ibuki', 'Priority', 'Sakura Empire', 'Heavy Cruiser', 0.5, 'CA', 'T*', 'AA' ],
	'Izumo':                          [ 'Izumo', 'Priority', 'Sakura Empire', 'Battleship', 0.5, 'BB*', 'CL/DD', 'AA' ],
	'Roon':                           [ 'Roon', 'Priority', 'Ironblood', 'Heavy Cruiser', 0, 'CA*', 'T', 'AA' ],
	'Saint_Louis':                    [ 'Saint Louis', 'Priority', 'Iris Libre', 'Heavy Cruiser', 0.5, 'CA', 'T', 'AA' ],
	'Seattle':                        [ 'Seattle', 'Priority', 'Eagle Union', 'Light Cruiser', 0, 'CL', 'CL/AA', 'AA' ],
	'Georgia':                        [ 'Georgia', 'Priority', 'Eagle Union', 'Battleship', 0, 'BB*', 'DD', 'AA' ],
	'Kitakaze':                       [ 'Kitakaze', 'Priority', 'Sakura Empire', 'Destroyer', 0, 'DD', 'T', 'AA' ],
	'Azuma':                          [ 'Azuma', 'Decisive', 'Sakura Empire', 'Large Cruiser', 0, 'CA/CB*', 'DD', 'AA' ],
	'Friedrich_der_Grosse':           [ 'Friedrich der Große', 'Decisive', 'Ironblood', 'Battleship', 0, 'BB', 'CL/DD', 'AA' ],
	'Gascogne':                       [ 'Gascogne', 'Priority', 'Vichya Dominion', 'Battleship', 0, 'BB', 'CL/DD', 'AA' ],
	'Cheshire':                       [ 'Cheshire', 'Priority', 'Royal Navy', 'Heavy Cruiser', 0, 'CA', 'T', 'AA' ],
	'Drake':                          [ 'Drake', 'Decisive', 'Royal Navy', 'Heavy Cruiser', 0, 'CA', 'T', 'AA' ],
	'Mainz':                          [ 'Mainz', 'Priority', 'Ironblood', 'Light Cruiser', 0, 'CL', 'T', 'AA' ],
	'Odin':                           [ 'Odin', 'Priority', 'Ironblood', 'Battlecruiser', 0.5, 'BB', 'T', 'AA' ],
	'Champagne':                      [ 'Champagne', 'Priority', 'Iris Libre', 'Battleship', 0, 'BB*', 'CL/DD', 'AA' ]
};

export default Object.keys( ships ).map( ( val ) => {
	const ship = ships[ val ];
	return {
		id:     val,
		name:   ship[ 0 ],
		link:   `https://azurlane.koumakan.jp/${ val }`,
		rarity: ship[ 1 ],
		nation: ship[ 2 ],
		type:   ship[ 3 ],
		tier:   ship[ 4 ],
		eq1:    ship[ 5 ],
		eq2:    ship[ 6 ],
		eq3:    ship[ 7 ]
	};
} );
